# tools/mqpet-convert/extract_items.py
"""Convert ItemData MonoBehaviour .asset files into a TS catalog module.
Price is re-tiered by effect strength (Unity left all at 100)."""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from guid_index import EXTRACTED

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
MB_DIR = os.path.join(EXTRACTED, "MonoBehaviour")
OUT = os.path.join(PROJECT_ROOT, "src", "shared", "mqpet-catalog.ts")

MAIN = {0: "Feeding", 1: "Function", 2: "DressUp"}
SUB = {0: "Food", 1: "Daily", 2: "Medicine", 3: "Other", 4: "Toy", 5: "Stats", 6: "Background", 7: "Props"}


def price_for(it):
    # Re-tier by combined effect magnitude (Unity left all at 100).
    mag = it["hunger"] + it["clean"] * 2 + it["health"] * 5 + it["mood"] + it["charm"] * 8
    if it["health"] >= 40 or it["charm"] >= 60:
        return 500
    if mag >= 3000:
        return 300
    if mag >= 800:
        return 150
    if mag >= 200:
        return 80
    return 50


def ts_str(s):
    # Produce a TS string literal with single quotes, escaping embedded quotes/backslashes.
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"


def parse(path):
    t = open(path, encoding="utf-8", errors="ignore").read()
    if "itemName:" not in t:
        return None

    def g(k, cast=str, default=0):
        m = re.search(rf"^\s*{k}:\s*(.*)$", t, re.M)
        return cast(m.group(1).strip()) if m else default

    name = g("itemName")
    if not name:
        return None
    it = dict(name=name, main=g("mainCategory", int), sub=g("subCategory", int),
              hunger=g("addHunger", int), clean=g("addCleanliness", int), health=g("addHealth", int),
              mood=g("addMood", int), charm=g("addCharm", int), growth=g("addGrowth", float, 0.0),
              buff=g("buffDuration", float, 0.0), unlock=g("unlockLevel", int, 1))
    it["price"] = price_for(it)
    return it


def main():
    items = []
    for fn in sorted(os.listdir(MB_DIR)):
        if fn.endswith(".asset"):
            it = parse(os.path.join(MB_DIR, fn))
            if it:
                items.append(it)
    items.sort(key=lambda x: (x["main"], x["sub"], x["unlock"], x["name"]))
    lines = [
        "// AUTO-GENERATED by tools/mqpet-convert/extract_items.py - do not edit by hand.",
        "// Source: QQpet_extracted MonoBehaviour ItemData assets. Prices re-tiered by effect strength.",
        "",
        "export type MqMainCategory = 'Feeding' | 'Function' | 'DressUp';",
        "export type MqSubCategory = 'Food' | 'Daily' | 'Medicine' | 'Other' | 'Toy' | 'Stats' | 'Background' | 'Props';",
        "",
        "export interface MqItem {",
        "  id: string;",
        "  name: string;",
        "  main: MqMainCategory;",
        "  sub: MqSubCategory;",
        "  price: number;",
        "  addHunger: number;",
        "  addCleanliness: number;",
        "  addHealth: number;",
        "  addMood: number;",
        "  addCharm: number;",
        "  addGrowth: number;",
        "  buffDuration: number;",
        "  unlockLevel: number;",
        "}",
        "",
        "export const MQ_ITEMS: MqItem[] = [",
    ]
    for it in items:
        lines.append(
            f"  {{ id: {ts_str(it['name'])}, name: {ts_str(it['name'])}, "
            f"main: '{MAIN[it['main']]}', sub: '{SUB[it['sub']]}', price: {it['price']}, "
            f"addHunger: {it['hunger']}, addCleanliness: {it['clean']}, addHealth: {it['health']}, "
            f"addMood: {it['mood']}, addCharm: {it['charm']}, addGrowth: {it['growth']}, "
            f"buffDuration: {it['buff']}, unlockLevel: {it['unlock']} }},")
    lines += [
        "];",
        "",
        "export const MQ_ITEM_BY_ID: Record<string, MqItem> = Object.fromEntries(MQ_ITEMS.map((i) => [i.id, i]));",
    ]
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {len(items)} items -> {OUT}")


if __name__ == "__main__":
    main()
