// AUTO-GENERATED by tools/mqpet-convert/extract_items.py - do not edit by hand.
// Source: QQpet_extracted MonoBehaviour ItemData assets. Prices re-tiered by effect strength.

export type MqMainCategory = 'Feeding' | 'Function' | 'DressUp';
export type MqSubCategory = 'Food' | 'Daily' | 'Medicine' | 'Other' | 'Toy' | 'Stats' | 'Background' | 'Props';

export interface MqItem {
  id: string;
  name: string;
  main: MqMainCategory;
  sub: MqSubCategory;
  price: number;
  addHunger: number;
  addCleanliness: number;
  addHealth: number;
  addMood: number;
  addCharm: number;
  addGrowth: number;
  buffDuration: number;
  unlockLevel: number;
}

export const MQ_ITEMS: MqItem[] = [
  { id: '经验丹', name: '经验丹', main: 'Feeding', sub: 'Food', price: 50, addHunger: 0, addCleanliness: 0, addHealth: 0, addMood: 0, addCharm: 0, addGrowth: 10.0, buffDuration: 0.0, unlockLevel: 1 },
  { id: '寿司', name: '寿司', main: 'Feeding', sub: 'Food', price: 80, addHunger: 500, addCleanliness: 0, addHealth: 0, addMood: 0, addCharm: 0, addGrowth: 0.0, buffDuration: 0.0, unlockLevel: 2 },
  { id: '汉堡', name: '汉堡', main: 'Feeding', sub: 'Food', price: 80, addHunger: 500, addCleanliness: 0, addHealth: 0, addMood: 0, addCharm: 0, addGrowth: 0.0, buffDuration: 0.0, unlockLevel: 2 },
  { id: '虾仁', name: '虾仁', main: 'Feeding', sub: 'Food', price: 50, addHunger: 50, addCleanliness: 0, addHealth: 0, addMood: 0, addCharm: 0, addGrowth: 0.0, buffDuration: 0.0, unlockLevel: 6 },
  { id: '鲣鱼', name: '鲣鱼', main: 'Feeding', sub: 'Food', price: 80, addHunger: 350, addCleanliness: 0, addHealth: 0, addMood: 0, addCharm: 0, addGrowth: 0.0, buffDuration: 0.0, unlockLevel: 6 },
  { id: '鲷鱼烧', name: '鲷鱼烧', main: 'Feeding', sub: 'Food', price: 150, addHunger: 800, addCleanliness: 0, addHealth: 0, addMood: 0, addCharm: 0, addGrowth: 0.0, buffDuration: 0.0, unlockLevel: 6 },
  { id: '黑盐', name: '黑盐', main: 'Feeding', sub: 'Food', price: 50, addHunger: 0, addCleanliness: 0, addHealth: 0, addMood: 0, addCharm: 0, addGrowth: 0.0, buffDuration: 0.0, unlockLevel: 6 },
  { id: '化妆桶', name: '化妆桶', main: 'Feeding', sub: 'Daily', price: 500, addHunger: 0, addCleanliness: 0, addHealth: 0, addMood: 0, addCharm: 100, addGrowth: 0.0, buffDuration: 43200.0, unlockLevel: 1 },
  { id: '口红', name: '口红', main: 'Feeding', sub: 'Daily', price: 80, addHunger: 0, addCleanliness: 0, addHealth: 0, addMood: 0, addCharm: 25, addGrowth: 0.0, buffDuration: 36000.0, unlockLevel: 1 },
  { id: '宝宝精华液', name: '宝宝精华液', main: 'Feeding', sub: 'Daily', price: 80, addHunger: 0, addCleanliness: 0, addHealth: 0, addMood: 500, addCharm: 20, addGrowth: 0.0, buffDuration: 36000.0, unlockLevel: 1 },
  { id: '沐浴露', name: '沐浴露', main: 'Feeding', sub: 'Daily', price: 300, addHunger: 0, addCleanliness: 3000, addHealth: 0, addMood: 0, addCharm: 0, addGrowth: 0.0, buffDuration: 0.0, unlockLevel: 1 },
  { id: '洗发水', name: '洗发水', main: 'Feeding', sub: 'Daily', price: 150, addHunger: 0, addCleanliness: 800, addHealth: 0, addMood: 0, addCharm: 0, addGrowth: 0.0, buffDuration: 0.0, unlockLevel: 1 },
  { id: '爽身粉', name: '爽身粉', main: 'Feeding', sub: 'Daily', price: 80, addHunger: 0, addCleanliness: 0, addHealth: 0, addMood: 0, addCharm: 25, addGrowth: 0.0, buffDuration: 36000.0, unlockLevel: 1 },
  { id: '牙膏', name: '牙膏', main: 'Feeding', sub: 'Daily', price: 150, addHunger: 0, addCleanliness: 400, addHealth: 1, addMood: 5, addCharm: 0, addGrowth: 0.0, buffDuration: 0.0, unlockLevel: 1 },
  { id: '礼品罐', name: '礼品罐', main: 'Feeding', sub: 'Daily', price: 80, addHunger: 0, addCleanliness: 0, addHealth: 0, addMood: 500, addCharm: 0, addGrowth: 0.0, buffDuration: 0.0, unlockLevel: 1 },
  { id: '紫罗兰药剂', name: '紫罗兰药剂', main: 'Feeding', sub: 'Daily', price: 80, addHunger: 0, addCleanliness: 0, addHealth: 0, addMood: 0, addCharm: 45, addGrowth: 0.0, buffDuration: 36000.0, unlockLevel: 1 },
  { id: '肥皂', name: '肥皂', main: 'Feeding', sub: 'Daily', price: 80, addHunger: 0, addCleanliness: 150, addHealth: 0, addMood: 0, addCharm: 20, addGrowth: 0.0, buffDuration: 54000.0, unlockLevel: 1 },
  { id: '被子', name: '被子', main: 'Feeding', sub: 'Daily', price: 150, addHunger: 0, addCleanliness: 300, addHealth: 5, addMood: 400, addCharm: 0, addGrowth: 0.0, buffDuration: 0.0, unlockLevel: 1 },
  { id: '钥匙扣', name: '钥匙扣', main: 'Feeding', sub: 'Daily', price: 50, addHunger: 0, addCleanliness: 0, addHealth: 0, addMood: 100, addCharm: 10, addGrowth: 0.0, buffDuration: 3600.0, unlockLevel: 1 },
  { id: '小风扇', name: '小风扇', main: 'Feeding', sub: 'Daily', price: 80, addHunger: 0, addCleanliness: 0, addHealth: 0, addMood: 200, addCharm: 0, addGrowth: 0.0, buffDuration: 0.0, unlockLevel: 5 },
  { id: '玫瑰香水', name: '玫瑰香水', main: 'Feeding', sub: 'Daily', price: 500, addHunger: 0, addCleanliness: 0, addHealth: 0, addMood: 0, addCharm: 80, addGrowth: 0.0, buffDuration: 36000.0, unlockLevel: 5 },
  { id: '迷迭香', name: '迷迭香', main: 'Feeding', sub: 'Daily', price: 80, addHunger: 0, addCleanliness: 0, addHealth: 0, addMood: 0, addCharm: 45, addGrowth: 0.0, buffDuration: 36000.0, unlockLevel: 5 },
  { id: '护发素', name: '护发素', main: 'Feeding', sub: 'Daily', price: 150, addHunger: 0, addCleanliness: 500, addHealth: 0, addMood: 200, addCharm: 0, addGrowth: 0.0, buffDuration: 0.0, unlockLevel: 6 },
  { id: '迷你香水', name: '迷你香水', main: 'Feeding', sub: 'Daily', price: 50, addHunger: 0, addCleanliness: 0, addHealth: 0, addMood: 0, addCharm: 10, addGrowth: 0.0, buffDuration: 3600.0, unlockLevel: 6 },
  { id: '香水01', name: '香水01', main: 'Feeding', sub: 'Daily', price: 80, addHunger: 0, addCleanliness: 0, addHealth: 0, addMood: 0, addCharm: 50, addGrowth: 0.0, buffDuration: 36000.0, unlockLevel: 6 },
  { id: '香水02', name: '香水02', main: 'Feeding', sub: 'Daily', price: 500, addHunger: 0, addCleanliness: 0, addHealth: 0, addMood: 0, addCharm: 67, addGrowth: 0.0, buffDuration: 36000.0, unlockLevel: 6 },
  { id: '爽肤露', name: '爽肤露', main: 'Feeding', sub: 'Daily', price: 150, addHunger: 0, addCleanliness: 1000, addHealth: 0, addMood: 0, addCharm: 0, addGrowth: 0.0, buffDuration: 0.0, unlockLevel: 8 },
  { id: '宠物礼盒', name: '宠物礼盒', main: 'Feeding', sub: 'Daily', price: 150, addHunger: 0, addCleanliness: 0, addHealth: 0, addMood: 1000, addCharm: 0, addGrowth: 0.0, buffDuration: 0.0, unlockLevel: 10 },
  { id: '护肤霜', name: '护肤霜', main: 'Feeding', sub: 'Daily', price: 80, addHunger: 0, addCleanliness: 0, addHealth: 0, addMood: 0, addCharm: 30, addGrowth: 0.0, buffDuration: 36000.0, unlockLevel: 10 },
  { id: '眼药水', name: '眼药水', main: 'Feeding', sub: 'Medicine', price: 50, addHunger: 0, addCleanliness: 0, addHealth: 5, addMood: 0, addCharm: 0, addGrowth: 0.0, buffDuration: 0.0, unlockLevel: 1 },
  { id: '印章', name: '印章', main: 'Feeding', sub: 'Other', price: 50, addHunger: 0, addCleanliness: 0, addHealth: 0, addMood: 0, addCharm: 10, addGrowth: 0.0, buffDuration: 3600.0, unlockLevel: 1 },
  { id: '钻石', name: '钻石', main: 'Feeding', sub: 'Other', price: 300, addHunger: 0, addCleanliness: 0, addHealth: 0, addMood: 3000, addCharm: 0, addGrowth: 100.0, buffDuration: 0.0, unlockLevel: 6 },
  { id: '占卜球', name: '占卜球', main: 'Feeding', sub: 'Toy', price: 80, addHunger: 0, addCleanliness: 0, addHealth: 0, addMood: 400, addCharm: 0, addGrowth: 0.0, buffDuration: 0.0, unlockLevel: 3 },
  { id: '天文望远镜', name: '天文望远镜', main: 'Feeding', sub: 'Toy', price: 80, addHunger: 0, addCleanliness: 0, addHealth: 0, addMood: 500, addCharm: 0, addGrowth: 0.0, buffDuration: 0.0, unlockLevel: 10 },
  { id: '火灵珠', name: '火灵珠', main: 'Feeding', sub: 'Stats', price: 500, addHunger: 0, addCleanliness: 0, addHealth: 50, addMood: 3000, addCharm: 67, addGrowth: 0.0, buffDuration: 0.0, unlockLevel: 30 },
];

export const MQ_ITEM_BY_ID: Record<string, MqItem> = Object.fromEntries(MQ_ITEMS.map((i) => [i.id, i]));
