const veryLongMimoText = `这是一个用于验证消息列不会截断的超长 MiMo 审查文本。重点确认：消息必须自动换行，任务卡和诊断摘要都要在自己的容器里独立滚动，重复活动在主界面合并为单条，同时保留 occurrenceCount、firstSeenAt、lastSeenAt 供诊断抽屉回放。文本里还包含一段超长路径 C:\\Users\\28219\\.agents\\skills\\teamflow\\diagnostics\\very-long-local-path\\runtime\\task-004\\review-output.json，用来确认 Windows 路径不会撑破卡片。`;

const runA = "run-20260502-220000-a1b2c3";
const runB = "run-20260501-194500-d4e5f6";

const tasks = [
  {
    runId: runA,
    id: "task-001",
    status: "COMPLETED",
    assignedAgent: "claude",
    title: "建立多会话真值模型",
    goal: "让每个会话的任务、事件、审查和诊断都按 run 隔离",
    scope: "src-tauri/src/lib.rs",
    attempts: 1,
    maxAttempts: 3,
    updatedAt: "2026-05-02T21:40:00+08:00",
  },
  {
    runId: runA,
    id: "task-002",
    status: "COMPLETED",
    assignedAgent: "claude",
    title: "补齐会话硬删除",
    goal: "运行中的会话先停止 Codex/Claude，再删除全量记录",
    scope: "src-tauri/src/lib.rs",
    attempts: 1,
    maxAttempts: 3,
    updatedAt: "2026-05-02T21:58:00+08:00",
  },
  {
    runId: runA,
    id: "task-003",
    status: "REVIEW_PENDING",
    assignedAgent: "claude",
    title: "完善诊断抽屉分区",
    goal: "按会话信息、关键动作、MCP、本地验证、MiMo、stderr、原始输出分区展示",
    scope: "web/src/App.jsx",
    attempts: 2,
    maxAttempts: 3,
    updatedAt: "2026-05-02T22:20:00+08:00",
  },
  {
    runId: runA,
    id: "task-004",
    status: "IN_PROGRESS",
    assignedAgent: "claude",
    title: "接入三阶段任务看板",
    goal: "待处理展示完整拆分任务，开发中展示当前 Claude 动作，MiMo 审核展示审查结果",
    scope: "web/src/App.jsx",
    attempts: 1,
    maxAttempts: 3,
    updatedAt: "2026-05-02T22:38:00+08:00",
  },
  {
    runId: runA,
    id: "task-005",
    status: "PENDING",
    assignedAgent: null,
    title: "验证 where.exe 闪窗回归",
    goal: "确认启动链路不再触发 where 或文件窗口反复弹出",
    scope: "scripts + src-tauri",
    attempts: 0,
    maxAttempts: 3,
    updatedAt: "2026-05-02T22:39:00+08:00",
  },
  {
    runId: runB,
    id: "task-001",
    status: "COMPLETED",
    assignedAgent: "claude",
    title: "历史会话隔离示例",
    goal: "验证切换会话后不会串任务或事件",
    scope: "web/src",
    attempts: 1,
    maxAttempts: 3,
    updatedAt: "2026-05-01T20:00:00+08:00",
  },
];

const dedupedAgentMessages = [
  {
    id: 11,
    runId: runA,
    sessionId: "codex-aaa111",
    agent: "codex",
    role: "assistant",
    kind: "thinking_started",
    text: "等待你输入项目目标后，我会先拆分完整任务清单，再按顺序派发给 Claude。",
    taskId: null,
    createdAt: "2026-05-02T22:15:00+08:00",
    occurrenceCount: 1,
    firstSeenAt: "2026-05-02T22:15:00+08:00",
    lastSeenAt: "2026-05-02T22:15:00+08:00",
  },
  {
    id: 12,
    runId: runA,
    sessionId: "codex-aaa111",
    agent: "codex",
    role: "assistant",
    kind: "task_delegated",
    text: "Codex 预览会话：已派发任务 004：接入三阶段任务看板。等待 Claude 执行并提交 MiMo 审查。",
    taskId: "task-004",
    createdAt: "2026-05-02T22:16:00+08:00",
    occurrenceCount: 1,
    firstSeenAt: "2026-05-02T22:16:00+08:00",
    lastSeenAt: "2026-05-02T22:16:00+08:00",
  },
  {
    id: 21,
    runId: runA,
    sessionId: "claude-bbb222",
    agent: "claude",
    role: "assistant",
    kind: "task_claimed",
    text: "已领取任务 004，开始实现三阶段看板和 Claude 对话流。",
    taskId: "task-004",
    createdAt: "2026-05-02T22:16:20+08:00",
    occurrenceCount: 1,
    firstSeenAt: "2026-05-02T22:16:20+08:00",
    lastSeenAt: "2026-05-02T22:16:20+08:00",
  },
  {
    id: 22,
    runId: runA,
    sessionId: "claude-bbb222",
    agent: "claude",
    role: "assistant",
    kind: "review_mimo",
    text: "MiMo 建议继续优化消息列宽度和活动去重提示。",
    taskId: "task-004",
    createdAt: "2026-05-02T22:19:00+08:00",
    occurrenceCount: 2,
    firstSeenAt: "2026-05-02T22:19:00+08:00",
    lastSeenAt: "2026-05-02T22:19:20+08:00",
  },
];

const dedupedEvents = [
  {
    id: "evt-001",
    runId: runA,
    type: "task_claimed",
    taskId: "task-004",
    message: "Claude 已领取任务 004",
    createdAt: "2026-05-02T22:16:20+08:00",
    firstSeenAt: "2026-05-02T22:16:20+08:00",
    lastSeenAt: "2026-05-02T22:16:20+08:00",
    occurrenceCount: 1,
    payload: {},
  },
  {
    id: "evt-002",
    runId: runA,
    type: "review_mimo",
    taskId: "task-004",
    message: veryLongMimoText,
    createdAt: "2026-05-02T22:19:00+08:00",
    firstSeenAt: "2026-05-02T22:19:00+08:00",
    lastSeenAt: "2026-05-02T22:19:20+08:00",
    occurrenceCount: 2,
    payload: {},
  },
];

export const mockRunGroups = [
  {
    group: "web\\src",
    hasMore: false,
    cursor: null,
    runs: [
      {
        runId: runA,
        title: "会话栏与任务看板",
        projectGoal: "只显示真实历史会话，并让任务看板使用同一份工作流真值",
        createdAt: "2026-05-02T21:30:00+08:00",
        updatedAt: "2026-05-02T22:40:00+08:00",
        lastActivityAt: "2026-05-02T22:40:00+08:00",
        total: 5,
        completed: 2,
        inProgress: 1,
        failed: 0,
        status: "RUNNING",
      },
      {
        runId: runB,
        title: "历史会话隔离",
        projectGoal: "验证切换会话后任务、事件、审查和诊断不串数据",
        createdAt: "2026-05-01T19:45:00+08:00",
        updatedAt: "2026-05-01T21:02:00+08:00",
        lastActivityAt: "2026-05-01T21:02:00+08:00",
        total: 1,
        completed: 1,
        inProgress: 0,
        failed: 0,
        status: "COMPLETED",
      },
    ],
  },
];

export const mockStatus = {
  currentRunId: runA,
  projectGoal: "构建 Teamflow Desktop 三栏工作台，完整展示任务、审查和诊断信息。",
  progressPercent: 40,
  database: "D:\\MCP\\teamflow\\runtime\\teamflow.sqlite3",
  tasksJson: "D:\\MCP\\teamflow\\runtime\\tasks.json",
  workspace: "D:\\MCP\\teamflow\\workspace",
  codexState: "RUNNING",
  codexModelSelection: {
    activeProviderId: "codex-gpt-5.5",
    activeProvider: {
      id: "codex-gpt-5.5",
      label: "默认 GPT-5.5",
      provider: "codex",
      model: "gpt-5.5",
      baseUrl: "https://ai.unclecode.cn",
      wireApi: "responses",
      apiKeyPresent: true,
    },
    providers: [
      {
        id: "codex-gpt-5.5",
        label: "默认 GPT-5.5",
        provider: "codex",
        model: "gpt-5.5",
        baseUrl: "https://ai.unclecode.cn",
        wireApi: "responses",
        apiKeyPresent: true,
      },
      {
        id: "mimo-v2.5-pro",
        label: "MiMo V2.5 Pro",
        provider: "mimo",
        model: "mimo-v2.5-pro",
        baseUrl: "https://token-plan-cn.xiaomimimo.com/v1",
        anthropicBaseUrl: "https://token-plan-cn.xiaomimimo.com/anthropic",
        envKey: "MIMO_API_KEY",
        wireApi: "chat",
        apiKeyPresent: true,
      },
    ],
  },
  codexBridgeState: {
    runId: runA,
    sessionId: "codex-aaa111",
    state: "active",
    sleeping: false,
    workerRunning: false,
    queueLength: 0,
    lastUserInputAt: "2026-05-02T22:38:00+08:00",
    lastBackendActivityAt: "2026-05-02T22:40:00+08:00",
    currentPid: null,
    lastRoundStartedAt: "2026-05-02T22:38:10+08:00",
    lastRoundEndedAt: "2026-05-02T22:39:22+08:00",
    roundState: "completed",
    roundActive: false,
  },
  codexRoundState: {
    runId: runA,
    state: "completed",
    active: false,
    source: "last",
    prompt: "请把中控显示对齐到真实任务工作流。",
    startedAt: "2026-05-02T22:38:10+08:00",
    endedAt: "2026-05-02T22:39:22+08:00",
    pid: 23456,
    exitCode: 0,
    interruptRequested: false,
  },
  activeCodexSessionId: "codex-aaa111",
  activeClaudeSessionId: "claude-bbb222",
  claudeWorkerState: {
    state: "RUNNING",
    globalRunning: 1,
    globalCap: 2,
    perRunCap: 1,
    queuedRuns: 1,
    runningRuns: 1,
    perRun: [
      { runId: runA, running: 1, queued: 1, failed: 0 },
      { runId: runB, running: 0, queued: 0, failed: 0 },
    ],
  },
  cliHealth: {
    codex: true,
    claude: true,
    mimoKey: true,
    sidecarPrepared: true,
    codexPath: "C:\\Users\\28219\\AppData\\Local\\OpenAI\\Codex\\bin\\codex.exe",
    claudePath: "C:\\Users\\28219\\AppData\\Roaming\\npm\\claude.cmd",
    sidecarPath: "D:\\MCP\\teamflow\\src-tauri\\teamflow-mcp-x86_64-pc-windows-msvc.exe",
    notes: [],
  },
  counts: {
    total: 5,
    PENDING: 1,
    IN_PROGRESS: 1,
    LOCAL_FAILED: 0,
    REVIEW_PENDING: 1,
    MIMO_REJECTED: 0,
    COMPLETED: 2,
    DEGRADED_PASS: 0,
    BLOCKED: 0,
    CANCELLED: 0,
  },
  workflowMetrics: {
    totalTasks: 5,
    completedTasks: 2,
    exceptionTasks: 0,
    progressPercent: 40,
    deliveryProgress: 2,
    currentGoal: "待处理展示完整拆分任务，开发中展示当前 Claude 动作，MiMo 审核展示审查结果",
    currentTaskId: "task-004",
    currentTaskTitle: "接入三阶段任务看板",
  },
  currentTask: tasks[3],
  tasks,
  dashboardPipeline: {
    pending: tasks.filter((task) => task.runId === runA),
    developing: tasks.filter((task) => task.runId === runA && ["IN_PROGRESS", "LOCAL_FAILED", "MIMO_REJECTED", "BLOCKED"].includes(task.status)),
    review: tasks.filter((task) => task.runId === runA && ["REVIEW_PENDING", "COMPLETED", "DEGRADED_PASS", "CANCELLED"].includes(task.status)),
  },
  dedupedAgentMessages,
  agentMessages: [],
  claudeTimelineSource: dedupedAgentMessages.filter((message) => message.agent === "claude"),
  dedupedEvents,
  events: [],
  rawEvents: [],
  reviews: [
    {
      id: 201,
      at: "2026-05-02T22:19:00+08:00",
      taskId: "task-004",
      kind: "review_mimo",
      status: "REJECTED",
      summary: "消息折叠与去重提示仍需增强。",
      payload: {},
    },
  ],
};

export const mockRunStatus = mockStatus;

export const mockDeleteResult = {
  runId: runA,
  deleted: {
    tasks: 5,
    events: 8,
    reviews: 3,
    agent_sessions: 2,
    agent_messages: 22,
    raw_transcripts: 30,
    process_events: 26,
    runs: 1,
  },
  interruptedSessions: ["codex-aaa111"],
  switchedToRunId: runB,
  createdRunId: null,
};

export const mockDiagnostics = {
  sessionId: "codex-aaa111",
  sessionInfo: {
    agent: "codex",
    status: "RUNNING",
    startedAt: "2026-05-02T22:15:00+08:00",
    endedAt: null,
    prompt: "Codex 桥接会话",
    lastError: null,
  },
  keyActions: [
    { id: 1, message: "任务 004 已派发给 Claude。" },
    { id: 2, message: "等待 Claude 执行并回传审查。" },
  ],
  mcpCalls: [{ id: 3, message: "delegate_task_and_wait(task-004)" }],
  localVerification: [{ id: 4, message: "npm --prefix web run web:build 通过" }],
  mimoReviews: [{ id: 5, message: veryLongMimoText }],
  stderr: [{ id: 6, stream: "stderr", chunk: "warning: field is never read" }],
  rawTranscripts: [{ id: 7, stream: "stdout", chunk: '{"type":"item.completed","item":{"type":"agent_message","text":"完成"}}' }],
  processEvents: [{ id: 8, message: "Codex 桥接已启动。" }],
};
